In [50]:
#Assignment-02a: Operations on NumPy Arrays
"""Context:
You are a data analyst working on a project to analyze health data collected from individuals.
Your task involves performing various operations on NumPy arrays to process and analyze the data effectively."""
#Task 1: Convert Weights to Pounds
#	Create a Python list weight_kg with weight values
weight_kg = [60,70,39,90,62,78]
print("print weight_kg list:",weight_kg)
#	Convert weight_kg to numpy array np_weight_kg
import numpy as np
np_weight_kg = np.array(weight_kg)
print("print np_weight_kg  numpy array: ",np_weight_kg)

#	Convert np_weight_kg to weight in Pounds np_weight_lbs
#Hint: Use the conversion factor of 2.2 pounds per kilogram
np_weight_lbs = np_weight_kg * 2.2
print("np_weight_lbs:",np_weight_lbs)

print weight_kg list: [60, 70, 39, 90, 62, 78]
print np_weight_kg  numpy array:  [60 70 39 90 62 78]
np_weight_lbs: [132.  154.   85.8 198.  136.4 171.6]


In [46]:
#Task 2: Calculate Mean and Median
#Write a NumPy program to calculate the mean and median of the weights in pounds.
#Print out the results.

np_weight_lbs_Mean = np.mean(np_weight_lbs)
print("np_weight_lbs_Mean:",np_weight_lbs_Mean)

np_weight_lbs_Median = np.median(np_weight_lbs)
print("np_weight_lbs_Median:",np_weight_lbs_Median)


np_weight_lbs_Mean: 120.63333333333334
np_weight_lbs_Median: 121.0


In [66]:
#Task 3: Create 2D Array
#       Create a NumPy array np_height_m containing the heights of individuals in meters.
np_height_m = np.array([1.70,1.59,1.8,1.68,1.65,1.38])
#       Combine this array with the weights in pounds np_weight_lbs to create a 2D array np_person_info ,
 # where each row represents an individual's height and weight.
np_person_info = np.column_stack((np_weight_lbs,np_height_m))
#       Print the resulting 2D array.
print(np_person_info)

#bmi_array = CalculateBmi(np_weight_kg, np_height_m) # test purpose

[[132.     1.7 ]
 [154.     1.59]
 [ 85.8    1.8 ]
 [198.     1.68]
 [136.4    1.65]
 [171.6    1.38]]


In [63]:
#Task 4: Calculate BMI
#Write a function that takes the 2D array np_person_info created in Task 3 as input.
def CalculateBmi(np_person_info):
   #Calculate the Body Mass Index (BMI) for each individual as bmi_array. BMI is calculated using the formula:
   #BMI = weight (kg) / (height (m) ** 2).
      height_m = np_person_info[:, 1]
      print(height_m)
      weight_kg = np_weight_kg
      print(weight_kg)
      bmi_array = weight_kg / (height_m ** 2)
   # Calculate BMI for each individual
   # Print the BMI values for each individual.
      print("BMI values:")
      for i in range(len(bmi_array)):
        print(f"Person {i+1}: {bmi_array[i]:.2f}")
        return bmi_array

CalculateBmi(np_person_info)

[1.7  1.59 1.8  1.68 1.65 1.38]
[60 70 39 90 62 78]
BMI values:
Person 1: 20.76


array([20.76124567, 27.68877813, 12.03703704, 31.8877551 , 22.77318641,
       40.95778198])

In [71]:
#Task 5: Filter Individuals by BMI
#       Write a NumPy program to append bmi_array to np_person_info ,Filter individuals from the resulting array who have a BMI greater than 25.
#       Print the filtered results.bmi_column = bmi_array.reshape(-1, 1)
def FilterByBmi(np_person_info, bmi_array):
    # Reshape bmi_array to be a column vector for concatenation
    bmi_column = bmi_array.reshape(-1, 1)

    # Append bmi_array to np_person_info
    # This creates a new array with height, weight, and BMI columns
    person_info_with_bmi = np.hstack((np_person_info, bmi_column))

   # print("Array shape after adding BMI:", person_info_with_bmi.shape)
   # print("First few rows with BMI:")
   # print(person_info_with_bmi[:3])

    # Determine BMI categories and print all individuals with their BMI and category
    print("\nIndividuals with BMI and Category:")
    print("Weight(lbs)  Height(m)  BMI          Category")
    for person in person_info_with_bmi:
        bmi = person[2]
        if 25 <  bmi :
            category = " Greater BMI 25"
        else:
            category = "Not filtered BMI"
        print(f"{person[0]:.2f}        {person[1]:.2f}      {bmi:.2f}      {category}")



FilterByBmi(np_person_info, bmi_array)


Individuals with BMI and Category:
Weight(lbs)  Height(m)  BMI          Category
132.00        1.70      20.76      Not filtered BMI
154.00        1.59      27.69       Greater BMI 25
85.80        1.80      12.04      Not filtered BMI
198.00        1.68      31.89       Greater BMI 25
136.40        1.65      22.77      Not filtered BMI
171.60        1.38      40.96       Greater BMI 25
